### PR TITLE
Migrate to Symfony

### PR DESCRIPTION
**Pull request by samwilson**
A new framework, to bring this into line with other tools and
simplify maintenance, and mainly to work towards resolving the
performance problems.

### CODE REVIEW

**Comment by samwilson** [comment]
@Nikerabbit You don't like Symfony?

**Comment by Nikerabbit** [comment]
Nothing against symfony, but this commit removed plural support from one message.

**Comment by samwilson** [comment]
Yeah I know. :-( It's a bug!

> An exception has been thrown during the rendering of a template ("User Error: Fatal error: [MessagesFunctions::plural] Invalid number argument to {{PLURAL: ...}}").

I didn't have time to dig into it on the weekend, and figured that this tool never runs with a contest or user count of less than dozens so it doesn't matter.

I'll fix it though! :-) I think it's related to a recent change I made to Intuition: https://github.com/Krinkle/intuition/pull/153

**Comment by Nikerabbit** [comment]
Even for larger numbers it does matter to some languages with more complicated rules than English: https://unicode-org.github.io/cldr-staging/charts/37/supplemental/language_plural_rules.html.

Thanks for looking into it.

**Comment by samwilson** [comment]
Okay, plurals have returned and are working correctly again. :-)

**Comment by Nikerabbit** [comment]
Big thanks! :heart_eyes:

**Pull request merged**
